### ISSUE TITLE
Flow Tracker Improvements

### ISSUE THREAD

**Issue by twood02** [sdnfv/openNetVM#238]
## Feature Request

The [`examples/flow_tracker`](https://github.com/sdnfv/openNetVM/tree/master/examples/flow_tracker) NF can be improved in several ways

**Describe the solution you'd like**

 - [ ] Should use `nf_function_table->setup` to setup state
 - [ ] Use nf->data field instead of global data
 - [ ] rename `clear_entries` to `clear_expired_entries`
 - [ ] better handle the case where flow table is full
 - [ ] Check if new DPDK hash table functions can simplify our code
 - [ ] Create a set of PCAP files to test correctness of this function
 - [ ] Improve output so that we can display info in a more condensed form
